### ISSUE TITLE
MoveIt in ROS Jazzy won't plan without joint accelerations

### ISSUE THREAD

**Issue by Nate711** [agilexrobotics/piper_ros#17]
https://github.com/agilexrobotics/piper_ros/blob/6c8dde2f662d60ecd9d72cad3c38420c4065acc6/src/piper_moveit/piper_no_gripper_moveit/config/joint_limits.yaml#L14

In ROS Jazzy when I launch `demo.launch.py` and click "Plan" in MoveIt RVIZ panel I get the following error

```sh
[move_group-2] [INFO] [1741738300.094172370] [move_group]: Calling Planner 'OMPL'
[move_group-2] [INFO] [1741738300.096611143] [move_group]: Calling PlanningResponseAdapter 'AddTimeOptimalParameterization'
[move_group-2] [ERROR] [1741738300.096649293] [move_group.moveit.moveit.core.time_optimal_trajectory_generation]: No acceleration limit was defined for joint joint5! You have to define acceleration limits in the URDF or joint_limits.yaml
[move_group-2] [ERROR] [1741738300.096668723] [move_group.moveit.moveit.ros.add_time_optimal_parameterization]: Response adapter 'AddTimeOptimalParameterization' failed to generate a trajectory.
[move_group-2] [ERROR] [1741738300.096684573] [move_group]: PlanningResponseAdapter 'AddTimeOptimalParameterization' failed with error code FAILURE
[move_group-2] [ERROR] [1741738300.096693723] [move_group.moveit.moveit.ros.move_group.move_action]: Generating a plan with planning pipeline failed.
[move_group-2] [INFO] [1741738300.096718833] [move_group.moveit.moveit.ros.move_group.move_action]: FAILURE
[rviz2-3] [INFO] [1741738300.096873262] [moveit_2701733468.moveit.ros.move_group_interface]: Planning request aborted
[rviz2-3] [ERROR] [1741738300.097573390] [moveit_2701733468.moveit.ros.move_group_interface]: MoveGroupInterface::plan() failed or timeout reached
```

After setting joint_limits.yaml like so it works
```yaml
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  joint2:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  joint3:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  joint4:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  joint5:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 50.0
  joint6:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 50.0
```
